### PR TITLE
Feature/setup code maintenance

### PR DESCRIPTION
**Pull request by yk-saito**
## What
Set up
- solhint
- eslint
- prettier
- CI

### CODE REVIEW

**Comment by wufengtao1** [comment]
I've reviewed the errors reported by Solhint, and there are no security issues in the contract code. It's just that the variable naming doesn't conform to Solhint's conventions. Do you think it's necessary to modify the contract code? If modifications are required, the corresponding test code will also need to be updated.

image

**Comment by neila** [comment]
@yk-saito will amend the code as well as the test script accordingly, so no need to take action on your end. 😌

**Comment by yk-saito** [comment]
@wufengtao1 

If I want to use `Next.js` for the front end, is there any way to launch it from ChainIDE?

The steps I have done are
1. `yarn dev`
2. Add Port 3000
3. Access

Screen Shot 2023-09-22 at 18 06 10

Error when accessing:

Screen Shot 2023-09-22 at 18 07 42


I have looked at the documentation [here](https://chainide.gitbook.io/chainide-english-1/port-forwarding), but it only supports truffle as described in the documentation?

**Comment by wufengtao1** [comment]
@yk-saito Hi, May I ask if your repository supports Node v16? Is there any error reported in the terminal? Port forwarding should not be limited to just Truffle; it should be supported for all.

**Comment by yk-saito** [comment]
> @yk-saito Hi, May I ask if your repository supports Node v16? Is there any error reported in the terminal? Port forwarding should not be limited to just Truffle; it should be supported for all.

I ran it again and was able to access it.
It seems it was taking a long time to reflect. Thanks 🙏

Screen Shot 2023-09-22 at 20 53 43

**Review by neila — APPROVED** [review]

**Pull request merged**
